version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - exptostd
    - fatcontext
    - gocritic
    - nilerr
    - nolintlint
    - nosprintfhostport
    - unparam
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    gocritic:
      disabled-checks:
        - commentFormatting
        - elseif
        - ifElseChain
        - mapKey
        - singleCaseSwitch
    govet:
      enable:
        - httpresponse
