syntax "next-router/0.1";

# ref: https://learn.microsoft.com/zh-cn/azure/foundry/openai/how-to/responses?tabs=rest

provider "azure-response" {
  defaults {
    upstream_config {
      # https://<resource>.cognitiveservices.azure.com
      base_url = "https://example-resource.cognitiveservices.azure.com";
    }

    auth {
      auth_header_key "api-key";
    }

    metrics {
      usage_extract openai_responses;
      finish_reason_extract openai_responses;
    }
    error {
      error_map openai;
    }
    response {
      resp_passthrough;
    }
  }

  match api = "chat.completions" {
    metrics {
      usage_extract openai_chat_completions;
      finish_reason_extract openai_chat_completions;
    }
    upstream {
      set_path "/openai/v1/chat/completions";
    }
  }

  match api = "responses" stream = true {
    metrics {
      usage_extract openai_responses_stream;
      finish_reason_extract openai_responses;
    }
    upstream {
      set_path "/openai/responses";
    }
  }

  match api = "responses" {
    upstream {
      set_path "/openai/responses";
    }
  }

}
